services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - 27017:27017  # Expose MongoDB's default port on the host
    volumes:
      - mongo_data:/data/db  # Mount the volume to persist data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false


  web:
    build: .
    command: python3 -m flask --debug --app core/nsa run -h 0.0.0.0 -p 5000 
    volumes:
      - .:/news_con/
    ports:
      - 5000:5000
    depends_on: ["mongo"]


volumes:
  mongo_data:
    driver: local
